[capability::agent_smith_use]
displayName = Use A.G.E.N.T. Smith investigations

[capability::agent_smith_admin]
displayName = Administer A.G.E.N.T. Smith configuration

[role_admin]
agent_smith_use = enabled
agent_smith_admin = enabled

[role_power]
agent_smith_use = enabled

[role_user]
agent_smith_use = enabled
